"""Accuracy regression guard.

Reads the baseline accuracy report at docs/accuracy_report.json and fails if
metrics regress beyond agreed margins. The report is regenerated by running
the pipeline against the test corpus (see accuracy_report.py) — this test
locks in the published baseline so prompt/code changes can't silently degrade
detection quality.
"""

import json
from pathlib import Path

import pytest

REPORT_PATH = Path(__file__).resolve().parent.parent / "docs" / "accuracy_report.json"

MIN_ACCURACY = 0.88
MIN_PRECISION = 0.85
MIN_RECALL = 0.85
MAX_FPR = 0.20


@pytest.fixture(scope="module")
def report():
    if not REPORT_PATH.exists():
        pytest.skip(f"baseline report missing: {REPORT_PATH}")
    return json.loads(REPORT_PATH.read_text())


def test_report_has_metrics(report):
    assert "metrics" in report
    assert "confusion_matrix" in report
    assert report["results"], "results list must not be empty"


def test_accuracy_above_threshold(report):
    acc = report["metrics"]["accuracy"]
    assert acc >= MIN_ACCURACY, f"accuracy {acc:.4f} below {MIN_ACCURACY}"


def test_precision_above_threshold(report):
    p = report["metrics"]["precision"]
    assert p >= MIN_PRECISION, f"precision {p:.4f} below {MIN_PRECISION}"


def test_recall_above_threshold(report):
    r = report["metrics"]["recall"]
    assert r >= MIN_RECALL, f"recall {r:.4f} below {MIN_RECALL}"


def test_fpr_below_ceiling(report):
    fpr = report["metrics"]["fpr"]
    assert fpr <= MAX_FPR, f"FPR {fpr:.4f} above {MAX_FPR}"


def test_confusion_matrix_consistent(report):
    cm = report["confusion_matrix"]
    total = cm["TP"] + cm["FP"] + cm["TN"] + cm["FN"]
    assert total == len(report["results"]), "confusion matrix totals must equal result count"
